# frozen_string_literal: true

Api::Application.routes.draw do
  namespace :enumerations do
    resources :attendance_status, only: %i[index show]
    resources :car_reservations_status, only: %i[index show]
    resources :contact_types, only: %i[index show]
    resources :content_tv_types, only: %i[index show]
    resources :event_dynamic_field_types, only: %i[index show]
    resources :event_status, only: %i[index show]
    resources :event_registration_status, only: %i[index show]
    resources :group_types, only: %i[index show]
    resources :integration_types, only: %i[index show]
    resources :layouts_space_bar, only: %i[index show]
    resources :local_reservation_status, only: %i[index show]
    resources :meeting_status, only: %i[index show]
    resources :operational_system_choice, only: %i[index show]
    resources :poll_status, only: %i[index show]
    resources :scholarship_formations, only: %i[index show]
    resources :scholarship_proof_status, only: %i[index show]
    resources :scholarship_proof_reprove_reasons, only: %i[index show]
    resources :scholarship_status, only: %i[index show]
    resources :scholarship_user_status, only: %i[index show]
    resources :scholarship_user_status_transfers, only: %i[index show]
    resources :shipping_interval_types, only: %i[index show]
    resources :solicitation_list_status, only: %i[index show]
    resources :solicitation_status, only: %i[index show]
    resources :solicitation_types, only: %i[index show]
    resources :space_types, only: %i[index show]
    resources :survey_ask_types, only: %i[index show]
    resources :survey_status, only: %i[index show]
    resources :tool_codes, only: %i[index show]
    resources :table_reservation_status, only: %i[index show]
    resources :tool_module_types, only: %i[index show]
    resources :tool_used_in, only: %i[index show]
    resources :user_ethnicities, only: %i[index show]
    resources :widget_types, only: %i[index show]
    resources :web_service_types, only: %i[index show]
  end
end
